name: cradle
description: "Build the framework for the cradle"

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12'
  destination-path:
    description: 'Path we copy the copier template into'
    required: false
    default: 'template'

runs:
  using: "composite"
  steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Update pip and install copier
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-cache-dir copier

      - name: Prepare git
        shell: bash
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "CI User"

      - name: Run copier
        working-directory: .
        shell: bash
        run: |
          copier copy --vcs-ref HEAD . ${{ inputs.destination-path }} --data-file .github/resources/data.yaml

      - name: Prepare the repo
        working-directory: ${{ inputs.destination-path }}
        shell: bash
        run: |
          git init -b main
          git add .
          git commit -m "Initial commit"
