#  Copyright 2025 Thomas Schmelzer
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

# GitHub Action to set up a new project using the cradle template
# This action uses copier to create a new project from the cradle template
name: cradle
description: "Build the framework for a new project using the cradle template"

inputs:
  python-version:
    description: 'Python version to use for the template and dependencies'
    required: false
    default: '3.12'  # Default to the latest stable Python version

  destination-path:
    description: 'Path where the copier template will be copied to'
    required: false
    default: 'template'  # Default destination directory

runs:
  using: "composite"  # Composite actions combine multiple steps
  steps:
      # Step 1: Check out the repository code
      # This ensures we have the latest code from the specified ref
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4  # Official GitHub checkout action

      # Step 2: Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Install copier tool
      # Copier is used to create a new project from a template
      - name: Update pip and install copier
        shell: bash
        run: |
          pip install --no-cache-dir copier  # Install copier without using cache

      # Step 4: Configure Git user information
      # This is needed for Git operations in the new repository
      - name: Prepare git
        shell: bash
        run: |
          # Set up Git user information for commits
          git config --global user.email "ci@example.com"
          git config --global user.name "CI User"

      # Step 5: Run copier to create the new project
      # This copies the template to the destination path
      - name: Run copier
        working-directory: .  # Run in the root directory
        shell: bash
        run: |
          # Copy the template to the destination path using the current HEAD as reference
          # and data from the data.yaml file
          copier copy --vcs-ref HEAD . ${{ inputs.destination-path }} --data-file .github/resources/data.yaml

      # Step 6: Initialize the new repository
      # This sets up the new project as a Git repository
      - name: Prepare the repo
        working-directory: ${{ inputs.destination-path }}  # Run in the destination directory
        shell: bash
        run: |
          # Initialize a new Git repository with main branch
          # This is necessary for pre-commit hooks to work properly
          # and for act to have a commit to work with
          git init -b main
          git add .
          git commit -m "Initial commit"
