# GitHub Action to run pre-commit hooks on all files in the repository
# This action ensures code quality and consistency by running all configured pre-commit hooks
name: Check all pre-commit hooks on all files
description: "Run all pre-commit hooks on all files in the repository to ensure code quality"

inputs:
  github_token:
    description: 'GitHub token for authentication to avoid rate limiting'
    required: false
    default: ''  # Empty string as default for optional token

runs:
  using: "composite"  # Composite actions combine multiple steps
  steps:
    # Step 1: Check out the repository code
    # This ensures we have the latest code from the specified ref
    - name: Checkout [${{ github.repository }}]
      uses: actions/checkout@v5  # Official GitHub checkout action

    # Step 2: Set up Node.js environment
    # This is required for some pre-commit hooks that use Node.js
    - name: Install Node 22
      uses: actions/setup-node@v6  # Official Node.js setup action
      with:
        node-version: '22'  # Use Node.js version 22

    # Step 3: Run all pre-commit hooks on all files
    # This executes all hooks defined in .pre-commit-config.yaml
    - uses: pre-commit/action@v3.0.1  # Official pre-commit GitHub Action
      with:
        extra_args: '--verbose --all-files'  # Run on all files with verbose output
        token: ${{ inputs.github_token }}  # Pass GitHub token if provided to avoid rate limiting
