# GitHub Action to compile LaTeX documents and deploy them
name: Compile and Deploy LaTeX Documents

description: "Advanced LaTeX document compilation with error handling, GitHub Pages deployment, and release creation"

inputs:
  tex-folder:
    description: "Folder containing the LaTeX file"
    required: false
    default: "paper"
  tex-file:
    description: "Main LaTeX file to compile (e.g. document.tex)"
    required: false
    default: "document.tex"

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "TEX_FOLDER=${{ inputs.tex-folder }}" >> $GITHUB_ENV
        echo "TEX_FILE=${{ inputs.tex-file }}" >> $GITHUB_ENV
        echo "TARGET_BRANCH=${{ inputs.target-branch }}" >> $GITHUB_ENV

    - name: Install Tectonic
      working-directory: ${{ env.TEX_FOLDER }}
      shell: bash
      run: |
        curl --proto '=https' --tlsv1.2 -fsSL https://drop-sh.fullyjustified.net | sh
        ./tectonic --version

    - name: Compile LaTeX document
      working-directory: ${{ env.TEX_FOLDER }}
      shell: bash
      run: |
        mkdir -p compiled
        echo "Compiling $TEX_FILE"
        ./tectonic "${{ env.TEX_FILE }}" --outdir compiled
        tree compiled

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: latex
        path: ${{ env.TEX_FOLDER }}/compiled/*.pdf
        retention-days: 1
