# GitHub Action to compile LaTeX documents and deploy them
name: Compile and Deploy LaTeX Documents

description: "Advanced LaTeX document compilation with error handling, GitHub Pages deployment, and release creation"

inputs:
  tex-folder:
    description: "Folder containing the LaTeX file"
    required: false
    default: "paper"
  tex-file:
    description: "Main LaTeX file to compile (e.g. document.tex)"
    required: false
    default: "document.tex"

runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "TEX_FOLDER=${{ inputs.tex-folder }}" >> $GITHUB_ENV
        echo "TEX_FILE=${{ inputs.tex-file }}" >> $GITHUB_ENV

    - name: Install Tectonic
      uses: wtfjoke/setup-tectonic@v3

    - name: Compile LaTeX document
      shell: bash
      working-directory: ${{ env.TEX_FOLDER }}
      run: |
        mkdir -p compiled
        tectonic ${{ env.TEX_FILE }} --outdir compiled
