# GitHub Action to compile LaTeX documents and deploy them
# This action compiles LaTeX files to PDF using Tectonic and can deploy them to GitHub Pages
name: Compile and Deploy LaTeX Documents

description: "Advanced LaTeX document compilation with error handling, GitHub Pages deployment, and release creation"

inputs:
  tag:
    description: 'Tag for creating a GitHub release (leave empty to skip release creation)'
    type: string
    required: false
    default: ''  # Empty by default,
