# GitHub Action to automatically bump version numbers and create releases
# This action analyzes commit messages to determine the next version number
name: "Bump version and create release"
description: "Automatically bumps version based on commit messages, creates a tag, and publishes a release"

inputs:
  github_token:
    description: "GitHub token for authentication with the repository"
    required: true
#    # No default provided as this should be passed from the workflow secrets

outputs:
  new_tag:
    description: "The newly created semantic version tag (e.g., v1.2.3)"
    value: ${{ steps.tag_version.outputs.new_tag }}

runs:
  using: "composite"  # Composite actions combine multiple steps

  steps:
    # Step 1: Bump version and create tag
    # This analyzes commit messages to determine the next version number
    # and creates a new tag with that version
    - name: Bump version and tag
      id: tag_version  # ID to reference outputs in later steps
      uses: mathieudutour/github-tag-action@v6.2  # Third-party version bumping action
      with:
        github_token: ${{ inputs.github_token }}
        #${{ secrets.github_token }}  # Token for authentication

    # Step 2: Create GitHub release for the new tag
    # This creates a release on GitHub with automatically generated release notes
    - name: Create GitHub release without artifacts
      uses: softprops/action-gh-release@v2  # Third-party release action
      with:
        token: ${{ inputs.github_token }}  # Token for authentication
        tag_name: ${{ steps.tag_version.outputs.new_tag }}  # Use the tag created in step 1
        generate_release_notes: true  # Automatically generate notes from commits
