name: Build the Jupyter Book
description: "Build jupyter book"

runs:
  using: "composite"

  steps:
    - name: Install jupyterbook
      shell: bash
      run: |
        uv pip install --no-cache-dir jupyter-book sphinx-math-dollar

    # Build the book
    - name: Build the book
      shell: bash
      run: |
        uv run jupyter-book clean book
        uv run jupyter-book build book

    # Upload the book
    - name: Archive book
      if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
      uses: actions/upload-artifact@v4
      with:
        name: book
        path: book/_build/html/
        retention-days: 1
