name: Build pdoc documentation
description: "Build pdoc documentation"

inputs:
  source-folder:
    description: 'Source folder to generate documentation for'
    type: string
    required: false
    default: 'cvx'
  pdoc-arguments:
    description: 'Additional pdoc command line arguments'
    type: string
    required: false
    default: ''


runs:


  using: "composite"
  steps:
    # Step 1: Set up the Python environment with uv (faster alternative to pip)
    # This step installs Python 3.12 and the uv package manager
    - name: Set up Python 3.12
      uses: astral-sh/setup-uv@v6  # Official action for setting up uv
      with:
        python-version: 3.12
        ignore-empty-workdir: true
        enable-cache: false
        version: '0.7.16'

    - name: Install and build pdoc
      shell: bash
      run: |
        uv pip install pdoc
        uv run pdoc -o artifacts/pdoc ${{ inputs.pdoc-arguments }} ${{ inputs.source-folder }}


    - name: Upload documentation
      if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
      uses: actions/upload-artifact@v4
      with:
        name: pdoc
        path: artifacts/pdoc
        retention-days: 1
