name: 'Age of Dependencies'
description: 'Run a check on the age of dependencies'

inputs:
  python-version:
    description: 'The Python we shall use'
    required: false
    default: '3.12'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install toml requests packaging pandas
        python -m pip install -e .
        mkdir -p artifacts/age

    - name: Check dependency ages
      shell: bash
      run: |
        python -m cradle.utils.age
        cat artifacts/age/dependency-age.txt

    - name: Upload test results
      if: ${{ env.ACT != 'true' }}  # Skip if running with 'act'
      uses: actions/upload-artifact@v4
      with:
        name: age
        path: artifacts/age
        retention-days: 1
