name: Build and Release Docker image
description: "Build the Docker image"

inputs:
  tag:
    description: 'The tag for the Docker image'
    required: true
  github_token:
    description: "GitHub token for authentication"
    required: true
  github_actor:
    description: "GitHub actor (username)"
    required: true
  github_repository:
    description: "GitHub repository name"
    required: true
  dockerfiles:
    description: "Location of the Dockerfile(s)"
    required: false
    default: 'docker/Dockerfile'
  registry:
    description: "Container registry URL"
    required: false
    default: "ghcr.io"
  labels:
    description: 'The labels of the image to build. Separate by newline. For example, "io.containers.capabilities=sys_admin,mknod".'
    required: false

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      uses: redhat-actions/podman-login@v1
      with:
          username: ${{ inputs.github_actor }}
          password: ${{ inputs.github_token }}
          registry: ${{ inputs.registry }}

    - name: Build image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ inputs.github_repository }}
        tags: ${{ inputs.tag }}
        dockerfiles: ${{ inputs.dockerfiles }}
        labels: ${{ inputs.labels }}

    - name: Push to ghcr.io
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ${{ inputs.registry }}
