#  Copyright 2025 Thomas Schmelzer
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
name: flow
description: "Test a flow"

inputs:
  workflow:
    description: 'Workflow, e.g. marimo.yml'
    required: true
  working-directory:
    description: 'Directory where the Python project is located'
    required: false
    default: 'template'

runs:
  using: "composite"
  steps:
    - name: Install act
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
        # Add the installation directory to PATH
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

    - name: Verify act installation
      shell: bash
      run: |
        act --version

    - name: Test workflow
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        git fetch origin 2>/dev/null || true
        act -W .github/workflows/${{ inputs.workflow}} -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest --env ACT='true'
