name: flow
description: "Test a flow"

inputs:
  workflow:
    description: 'Workflow, e.g. marimo.yml'
    required: true
  working-directory:
    description: 'Directory where the Python project is located'
    required: false
    default: 'template'

runs:
  using: "composite"
  steps:
    - name: Install act
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash
        # Add the installation directory to PATH
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

    - name: Verify act installation
      shell: bash
      run: |
        act --version

    - name: Test workflow
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        act -W .github/workflows/${{ inputs.workflow }} -P ubuntu-22.04=ghcr.io/tschm/cradle:latest --env ACT='true' 2>&1 | grep -v "remote not found"
