name: 'Dependency Check'
description: 'Run deptry to check for dependency issues'

inputs:
  source-folder:
    description: 'Source folder to analyze'
    required: true
  options:
    description: 'Extra options for deptry'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4
        
    - name: Set up Python 3.12
      uses: astral-sh/setup-uv@v6  # Official action for setting up uv

    - name: Run Deptry
      shell: bash
      run: |
        uvx deptry ${{ inputs.source-folder }} ${{ inputs.options }}
