name: 'Dependency Check'
description: 'Run deptry to check for dependency issues'

inputs:
  source-folder:
    description: 'Source folder to analyze'
    required: true
  options:
    description: 'Extra options for deptry'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    # Step 1: Set up the Python environment with uv (faster alternative to pip)
    # This step installs Python 3.12 and the uv package manager
    - name: Set up Python 3.12
      uses: astral-sh/setup-uv@v6  # Official action for setting up uv

    - name: Run Deptry
      shell: bash
      run: |
        uvx deptry ${{ inputs.source-folder }} ${{ inputs.options }}
