name: 'Dependency Check'
description: 'Run deptry to check for dependency issues'

inputs:
  source-folder:
    description: 'Source folder to analyze'
    required: false
    default: 'cvx'
  options:
    description: 'Extra options for deptry'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Install deptry
      shell: bash
      run: |
        uv pip install --no-cache-dir deptry

    - name: Run Deptry
      shell: bash
      run: deptry ${{ inputs.source-folder }} ${{ inputs.options }}
