name: Build the book
description: "Build the book"

permissions:
  contents: write
  pages: write

runs:
  using: "composite"

  steps:
    - name: Download all artifacts
      if: ${{ env.ACT != 'true' }}
      uses: actions/download-artifact@v4
      with:
        path: .book

    - name: Create .nojekyll
      shell: bash
      run: touch .book/.nojekyll

    - name: GitHub Pages action
      if: ${{ env.ACT != 'true' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .book
