name: Build Environment
description: "Build the environment using pyproject.toml and uv"

inputs:
  python-version:
    description: 'The Python version to use'
    required: false
    default: '3.12'

runs:
  using: "composite"

  steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python-version }}
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        set -euo pipefail

        if [ -f "requirements.txt" ]; then
          echo "🔧 Using requirements.txt — syncing environment"
          uv sync --frozen
        elif [ -f "pyproject.toml" ]; then
          echo "📦 Using pyproject.toml — syncing environment"
          if [ -f "uv.lock" ]; then
            uv sync --frozen --all-extras
          else
            echo "⚠️  No uv.lock file found — proceeding without lockfile"
            uv pip install --require-virtualenv
          fi
        else
          echo "❌ No requirements.txt or pyproject.toml found"
          exit 1
        fi
