# GitHub Action to set up a Python development environment
# This action installs all dependencies defined in pyproject.toml or requirements.txt using uv
name: Build Environment
description: "Build the Python development environment using pyproject.toml or requirements.txt with uv package manager"

inputs:
  python-version:
    description: 'The Python version to use for the environment (e.g., 3.9, 3.10, 3.11, 3.12)'
    required: false
    default: '3.12'  # Default to the latest stable Python version
  use-requirements-txt:
    description: 'Whether to use requirements.txt instead of pyproject.toml'
    required: false
    default: 'false'
  requirements-path:
    description: 'Path to the requirements.txt file'
    required: false
    default: 'requirements.txt'

runs:
  using: "composite"  # Composite actions combine multiple steps

  steps:
    # Step 1: Check out the repository code
    # This ensures we have the latest code from the specified ref
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4  # Official GitHub checkout action

    # Step 2: Set up Python with the uv package manager
    # This installs Python and uv for faster dependency management
    - name: Set up Python ${{ inputs.python-version }}
      uses: astral-sh/setup-uv@v6  # Official action for setting up uv
      with:
        python-version: ${{ inputs.python-version }}  # Use the specified Python version

    # Step 3: Install all dependencies from pyproject.toml or requirements.txt
    # This uses uv to install dependencies faster than pip
    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.use-requirements-txt }}" == "true" ]; then
          # Install dependencies from requirements.txt
          echo "Installing dependencies from ${{ inputs.requirements-path }}"
          uv pip install -r ${{ inputs.requirements-path }}
        else
          # Install all dependencies including optional extras from pyproject.toml
          # This is equivalent to pip install -e ".[all]" but much faster
          echo "Installing dependencies from pyproject.toml"
          uv sync --all-extras
        fi
