name: Build Environment
description: "Build the environment using pyproject.toml and uv"

inputs:
  python-version:
    description: 'The Python version to use'
    required: false
    default: '3.12'

runs:
  using: "composite"

  steps:
    - name: Checkout ${{ github.repository }}
      uses: actions/checkout@v4

    - name: Set up Python ${{ inputs.python-version }}
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        uv sync --all-extras
