name: minibook.yml

on:
  push

jobs:
  mini:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4

      # Step 2: Create minibook
      - name: Minibook
        uses: ./actions/minibook
        with:
          links: "spiegel;https://www.spiegel.de"
